services:
  redis:
    container_name: madoka_redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./backup/redis:/data

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "6378:5540"
