services:
  db:
    container_name: db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      TZ: Asia/Bangkok
    ports:
      - 3306:3306
    volumes:
      - "./data:/var/lib/mysql"
    networks:
      - database

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 3307:8080
    environment:
      ADMINER_DESIGN: 'dracula'
    networks:
      - database

networks:
  database:
    driver: bridge
