version: "3.1"

services:
  database:
    container_name: morty
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      TZ: Asia/Bangkok
    ports:
      - 3306:3306
    volumes:
      - "database:/var/lib/mysql"
    secrets:
       - db_root_password
  adminer:
    image: adminer
    restart: always
    ports:
      - 3307:8080
    environment:
      ADMINER_DESIGN: 'dracula'

volumes:
  database:
    name: database
    driver: local

secrets:
  db_root_password:
    file: ./password.txt
