version: "3.1"

services:
  db:
    container_name: db
    image: mysql
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      TZ: Asia/Bangkok
    ports:
      - 3306:3306
    volumes:
      - "database:/var/lib/mysql"
    secrets:
      - db_root_password
    networks:
      - database

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 3307:8080
    environment:
      ADMINER_DESIGN: 'dracula'
    networks:
      - database

networks:
  database:
    driver: bridge

volumes:
  database:
    name: database
    driver: local

secrets:
  db_root_password:
    file: ./password
