services:
  db:
    container_name: db
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD: 12345678
    ports:
      - 3306:3306
    volumes:
      - "./data:/var/lib/mysql"

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 3307:8080
    environment:
      ADMINER_DESIGN: 'dracula'
