#!/bin/bash

# ตรวจสอบว่ามี argument ส่งเข้ามาหรือไม่
if [ -z "$1" ]; then
  echo "No argument supplied"
  return
fi

if [ $SHELL = "/bin/bash" ] || [ $SHELL = "/usr/bin/bash" ]; then
  File=~/.bashrc
elif [ $SHELL = "/bin/zsh" ] || [ $SHELL = "/usr/bin/zsh" ]; then
  File=~/.zshrc
fi

if [ -z $WS_CMD ]; then
  PATH=$(dirname "$(realpath "$0")")
  echo "" >> $File
  echo "# Workspaces" >> $File
  echo "export WS_CMD=$PATH" >> $File
  echo "source \$WS_CMD/script" >> $File
  echo "source \$WS_CMD/config" >> $File
  . $File
fi

if [ $1 = "dev" ] && [ -d $2 ]; then
  echo "" >> $File
  echo "# Dev Path" >> $File
  echo "export DEV=$2" >> $File
fi
