#!/bin/bash

# ตรวจสอบว่ามี argument ส่งเข้ามาหรือไม่
if [ -z "$1" ]; then
  echo "No argument supplied"
  return
fi

# ตรวจสอบว่า shell ที่ใช้อยู่คือ bash หรือ zsh
if [ "$SHELL" = "/bin/bash" ] || [ "$SHELL" = "/usr/bin/bash" ]; then
  echo -e "\n# My Path \nexport DEV=$1" >> ~/.bashrc
  echo -e "export DEV_CMD=$PWD" >> ~/.bashrc
  echo -e "source \$DEV_CMD/script" >> ~/.bashrc
  source ~/.bashrc
elif [ "$SHELL" = "/bin/zsh" ] || [ "$SHELL" = "/usr/bin/zsh" ]; then
  echo -e "\n# My Path \nexport DEV=$1" >> ~/.zshrc
  echo -e "export DEV_CMD=$PWD" >> ~/.zshrc
  echo -e "source \$DEV_CMD/script" >> ~/.zshrc
  source ~/.zshrc
else
  echo "Unsupported shell: $SHELL"
fi
