#!/bin/bash

# ตรวจสอบว่า shell ที่ใช้อยู่คือ bash หรือ zsh
if [ "$SHELL" = "/bin/bash" ] || [ "$SHELL" = "/usr/bin/bash" ]; then
  echo -e "\n# Podman \nexport PATH=\$PATH:\$DEV_CMD/docker" >> ~/.bashrc
  source ~/.bashrc
elif [ "$SHELL" = "/bin/zsh" ] || [ "$SHELL" = "/usr/bin/zsh" ]; then
  echo -e "\n# Podman \nexport PATH=\$PATH:\$DEV_CMD/docker" >> ~/.zshrc
  source ~/.zshrc
else
  echo "Unsupported shell: $SHELL"
fi
