services:
  db:
    container_name: rin-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
    volumes:
      - ./backup/postgres:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - "5431:8080"
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: db
