services:
  redis:
    container_name: rin_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./backup/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
