services:
  db:
    container_name: rin-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
    volumes:
      - ./backup/postgres:/var/lib/postgresql/data
