services:
  beaver:
    container_name: roxy_beaver
    image: dbeaver/cloudbeaver:latest
    restart: always
    environment:
      SERVER_ANONYMOUS_ACCESS_ENABLED: true
    ports:
      - "9090:8978"
    volumes:
      - ./backup/workspace:/opt/cloudbeaver/workspace
