services:
  adminer:
    container_name: roxy_adminer
    image: adminer:latest
    ports:
      - "9090:8080"
    environment:
      ADMINER_DESIGN: haeckel
    volumes:
      - ./plugins:/var/www/html/plugins-enabled
      - ./backup/config:/var/www/html/config
